version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/VOETBAL-FRONTEND
    ports:
      - 3000:3000
    image: app:react
    container_name: VOETBAL-FRONTEND_container
    command: npm start